### ISSUE TITLE
--continue_train will start from epoch 0?

### ISSUE THREAD

**Issue by Ha0Tang** [boschresearch/OASIS#1]

**Comment by edgarschnfld** [comment]
Hi,

The epoch from which to continue is set with the ```--which_iter ``` flag. To see what value to feed to this flag you have to look into the ```checkpoints/experiment_name/models``` folder. The checkpoints that are saved in this folder have names like ```80000_G.pth```, ```120000_G.pth``` and so on, where the number corresponds to the iteration in which it was saved. How often checkpoints are saved is controlled with ```--freq_save_ckpt```. The overall best model is saved as ```best_G.pth```, the most recent one with  ```latest_G.pth```. This means when you want to continue training you should combine  ```--continue_train``` with ```--which_iter latest```. Training will then resume from the last epoch and iteration. 
P.S.: Until now ```--which_iter``` only accepted a number or "latest". I patched it now so it also accepts "best" as which_iter.

**Comment by SushkoVadim** [comment]
Hi,

Adding my 5 cents, the option `--continue_train` can be also used without `--which_iter`. It will load the "latest" checkpoints and will start from iteration stored  in `checkpoints/experiment_name/latest_iter.txt`.

So the simplest way to resume previously interrupted experiment is to run
`python train.py --name exp_name --continue_train`

**Comment by Ha0Tang** [comment]
@edgarschnfld @SushkoVadim I mean the screen print starts from epoch 0 after the interrupted.

**Comment by Ha0Tang** [comment]
@edgarschnfld @SushkoVadim It seems that simply adding --continue_train and --which_iter latest is not working, can you double-check it?

**Comment by Ha0Tang** [comment]
I mean, if the training interrupted at epoch 81, do we need to set `start_epoch` in this line https://github.com/boschresearch/OASIS/blob/1cf88823d825bc95341ab6e7b235b680265de9cf/train.py#L33 to 81 for the continuing train.

**Comment by edgarschnfld** [comment]
I just tried to replicate what you experience. So I cloned the repo, made a folder ```OASIS/checkpoints``` and copied ```oasis_ade20k_pretrained``` into it. Then I ran the following command:  

```
python train.py --name oasis_ade20k_pretrained --dataset_mode ade20k --gpu_ids 0,1,2,3 \
--dataroot $SSD/ADEChallengeData2016 --batch_size 12 --continue_train --which_iter best --num_epochs 300
```

This works perfectly for me. Setting ```--which_iter``` to something else like ```40000``` works too (I have those intermediate checkpoints but we did not upload them here). 

Things to consider here: 
1. ``` --name``` should match the folder name of the checkpoint. 
2. The ```--num_epochs 300``` is necessary if training had already finished naturally, because the pre-trained checkpoint had reached its maximum number of epochs of 200. The training stops automatically when ```num_epochs``` is reached, so ```--num_epochs bigger-number``` needs to specified in this case or else training terminates. Then it trains normally. 
3. ```start_epoch, start_iter = utils.get_start_iters(opt.loaded_latest_iter, len(dataloader)) ``` automatically loads the total iteration number and computes which epoch and iter that corresponds to (caveat - if you resume with another batch size then the start epoch will be miscalculated). If no number is specified, it reads ```/checkpoints/your_experiment_name/latest_iter.txt``` to find the latest iter. A similar thing happens when you specify "best". In theory, you could manually set the start_epoch and start_iter manually in the line you pointed out, for example to 81 and 0.

In addition to this, I also made a little toy experiment where I train from scratch, skim through some epochs in a short time, stop training and then continue, and it loads epoch and iter correctly.  

Can you describe your situation more - what do you observe? 

Feel also free to answer some of the questions below:
Do you have checkpoints saved in ```/checkpoints/your_experiment_name/models/``` ? 
Did you change the name of the auto-generated checkpoints?  
Does the checkpoint load and training resumes, but when you print the epoch it says 0?  
Or does the checkpoint not load at all too?  
Are there error messages? 
Is the ```--name``` different from the one from where you load the checkpoint? 
Do you manually set the ```checkpoints_dir``` to some other folder?

**Comment by Ha0Tang** [comment]
My bad, I used a different batch size to continually train.
