### ISSUE TITLE
Is there any way to shorten the training time？

### ISSUE THREAD

**Issue by Ha0Tang** [boschresearch/OASIS#3]

**Comment by edgarschnfld** [comment]
There is the branch ```ddp_amp```. If you switch to this branch and run ```python train_ddp_apex.py --your_usual_arguments``` then it trains with DistributedDataParallell (instead of DataParallel) and mixed-precision training. It's not really tested yet, and I would advise to switch off the mixed-precision part, since it gave weird results. However, the DistributedDataParallel training should be faster in theory. Use it at your own risk, since I didn't have time to test, let alone benchmark it yet.
